version: '3.9'

services:
  redis:
    image: redis:6.2.6
    networks:
      - redis_network
    restart: unless-stopped
  api:
    build:
      context: .
    command: bash -c "
        python manage.py collectstatic --noinput &&
        gunicorn api.wsgi -c gunicorn_conf.py
      "
    env_file:
      - .env
    volumes:
      - /tmp/static:/api/staticfiles
    ports:
      - 8000:8000
    depends_on:
      - redis
    networks:
      - redis_network
      - nginx_network
    restart: unless-stopped
  web:
    build:
      context: web
    volumes:
      - web_volume:/frontend/build
  nginx:
    image: nginx:1.21.6
    depends_on:
      - api
      - web
    env_file:
      - .env
    environment:
      NGINX_ENVSUBST_TEMPLATE_SUFFIX: .conf
    ports:
      - 80:80
      - 443:443
    volumes:
      - /tmp/static:/staticfiles
      - web_volume:/html
      - ./nginx.conf.conf:/etc/nginx/templates/nginx.conf.conf
      - ./certs:/certs
    networks:
      - nginx_network
    restart: unless-stopped
  celery:
    build:
      context: .
    command: celery -A api worker -c 3 -P gevent -l info
    env_file:
      - .env
    depends_on:
      - nginx
    networks:
      - redis_network
    restart: unless-stopped
  celery_beat:
    build:
      context: .
    command: celery -A api beat -S django -l info
    env_file:
      - .env
    depends_on:
      - celery
    networks:
      - redis_network
    restart: unless-stopped

volumes:
  - web_volume:

networks:
  redis_network:
  nginx_network:
