# Generated by Django 3.2.2 on 2022-06-07 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    
    initial = True
    
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('air', '0003_alter_query_flight_class'),
    ]
    
    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True, primary_key=True, serialize=False,
                    verbose_name='ID'
                )),
                ('query', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, related_name='favorites',
                    to='air.query'
                )),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, related_name='favorites',
                    to=settings.AUTH_USER_MODEL
                )),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
                'unique_together': {('user', 'query')},
            },
        ),
    ]
