# Generated by Django 3.2.2 on 2022-05-12 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_class', models.PositiveSmallIntegerField(choices=[('y', 'Эконом'), ('c', 'Бизнес')])),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QueryTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='querytrips_by_destination', to='geo.city')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='querytrips_by_origin', to='geo.city')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='air.query')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
