# Generated by Django 3.2.2 on 2022-05-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air', '0002_auto_20220514_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='flight_class',
            field=models.TextField(choices=[('Y', 'Эконом'), ('C', 'Бизнес')]),
        ),
    ]
