# Generated by Django 3.2.2 on 2022-04-30 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('air', '0001_initial'),
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gate_id', models.IntegerField()),
                ('title', models.TextField()),
                ('price', models.FloatField()),
                ('url', models.IntegerField()),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign', models.TextField(unique=True)),
                ('best_offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_by_best_offer', to='tickets.offer')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='air.query')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('transfer_time', models.IntegerField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_by_destination', to='geo.city')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_by_origin', to='geo.city')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.ticket')),
                ('transfer_airports', models.ManyToManyField(related_name='trip_by_transfer_airports', to='geo.Airport')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('flight', models.TextField()),
                ('handbags_weight', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('baggage_weight', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('arrival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segment_by_arrival', to='geo.airport')),
                ('departure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segment_by_departure', to='geo.airport')),
                ('marketing_airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.airline')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.trip')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='offer',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.ticket'),
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft', models.TextField(blank=True, null=True)),
                ('food', models.BooleanField(blank=True, null=True)),
                ('entertainment', models.BooleanField(blank=True, null=True)),
                ('alcohol', models.BooleanField(blank=True, null=True)),
                ('beverage', models.BooleanField(blank=True, null=True)),
                ('power', models.BooleanField(blank=True, null=True)),
                ('wifi', models.BooleanField(blank=True, null=True)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.airline')),
                ('segment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tickets.segment')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='offer',
            unique_together={('ticket', 'gate_id')},
        ),
    ]
