# Generated by Django 3.2.2 on 2022-05-29 09:34

from django.db import migrations


class Migration(migrations.Migration):
    
    dependencies = [
        ('tickets', '0002_auto_20220514_1749'),
    ]
    
    operations = [
        migrations.RemoveField(
            model_name='segment',
            name='baggage_weight',
        ),
        migrations.RemoveField(
            model_name='segment',
            name='handbags_weight',
        ),
    ]
