# Generated by Django 3.2.2 on 2022-05-29 09:50
from datetime import timedelta

from django.db import migrations, models


class Migration(migrations.Migration):
    
    dependencies = [
        ('tickets', '0003_auto_20220529_0934'),
    ]
    
    operations = [
        migrations.AddField(
            model_name='trip',
            name='duration',
            field=models.DurationField(default=timedelta(minutes=1)),
            preserve_default=False,
        ),
    ]
