# Generated by Django 3.2.2 on 2022-05-30 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    
    dependencies = [
        ('tickets', '0004_trip_duration'),
    ]
    
    operations = [
        migrations.AddField(
            model_name='ticket',
            name='travel_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
